###
GET http://127.0.0.1:8000/api/lead/
Authorization: Basic admin:admin
###
POST http://127.0.0.1:8000/api/lead/
Content-Type: application/json

{
    "first_name":"Govind",
    "last_name":"Krishna",
    "email":"goku@gmail.com",
    "phone":"8491849234",
    "dob":"13223",
    "qualification":"BTECH",
    "passout_year":"2024",
    "follow_up_date":"2025"
}

###
DELETE  http://127.0.0.1:8000/api/lead/3/